services:
  swarmui:
    image: swarmui
    build:
      context: .
      dockerfile: launchtools/StandardDockerfile.docker
    container_name: swarmui
    # uncomment `network_mode: host` if you want to access other services on the host network (eg a separated comfy instance)
    # network_mode: host
    volumes:
      - swarmdata:/Data
      - swarmbackend:/dlbackend
      - swarmdlnodes:/src/BuiltinExtensions/ComfyUIBackend/DLNodes
      - ./Models:/Models
      - ./Output:/Output
      - ./src/BuiltinExtensions/ComfyUIBackend/CustomWorkflows:/src/BuiltinExtensions/ComfyUIBackend/CustomWorkflows
    ports:
      - "7801:7801"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # change the count to the number of GPUs you want to use.
              count: 1
              capabilities: [gpu]
volumes:
  swarmdata:
  swarmbackend:
  swarmdlnodes:
