name: Bug Report
description: "Something is broken inside of SwarmUI. (Do not use this if you're just having issues and need help)"
labels: [ "Bug" ]
body:
    - type: markdown
      attributes:
        value: |
                Before submitting a **Bug Report**, please ensure the following:

                **1:** You are running the latest version of SwarmUI. You can go to `Server` -> then press `Update and Restart` to update.
                **2:** You have looked at the existing bug reports and made sure this isn't already reported.
                **3:** This is an actual bug in SwarmUI, not just a support question and not caused by an extension. A bug is when you can specify exact steps to replicate what went wrong and others will be able to repeat your steps and see the same issue happen.

                If unsure, ask on the [SwarmUI Discord](https://discord.gg/q2y38cqjNw) first.
    - type: textarea
      attributes:
            label: Expected Behavior
            description: "What you expected to happen."
      validations:
            required: true
    - type: textarea
      attributes:
                label: Actual Behavior
                description: "What actually happened. Please include a screenshot of the issue if possible."
      validations:
                required: true
    - type: textarea
      attributes:
                label: Steps to Reproduce
                description: "How to reproduce the issue. Any specific parameters to use, any required extensions, etc."
      validations:
                required: true
    - type: textarea
      attributes:
                label: Debug Logs
                description: "Please go to `Server` -> `Logs` -> then click the `Pastebin` button and copy the link it generates for you to here. Alternately, set `View Type` to `Debug`, then copypaste all the text into here. If Swarm isn't starting, copy the logs from the terminal window if you can."
                render: powershell
      validations:
                required: true
    - type: textarea
      attributes:
                label: Other
                description: "Any other additional information you think might be helpful."
      validations:
                required: false
